### ISSUE TITLE
Adding the tests

### ISSUE THREAD

**Issue by gerra** [IFMO-MobDev-2014/lesson4#26]
"Вы должны добавить тесты на вашу реализацию CalculationEngine" it means that i should add lines like "Assert.assertEquals(2d, CalculationEngineFactory.defaultEngine().calculate("1+1"));" to DummyTest.java?
And what epsilon we should use for determine division by zero? Or we should ignore it and write Infinity or something like 1E-5?

**Comment by svasilinets** [comment]
It is better to add a separate file for tests.

You can use eps like 1e-5, but as it was mentioned earlier, we are not going to add tests, that will catch you on the accuracy of a calculation.
