### ISSUE TITLE
Библиотека для парсинга выражений

### ISSUE THREAD

**Issue by EvgeniyaKatunina** [IFMO-MobDev-2014/lesson4#4]
Можно ли использовать собственную библиотеку для парсинга выражений или нужно парсить кодом этого же проекта?

**Comment by thevery** [comment]
А что за собственная библиотека?
Нужно чтобы проект умел собираться локально в первую очередь.

**Comment by EvgeniyaKatunina** [comment]
У меня есть готовая библиотека для парсинга выражений, оставшаяся с домашней работы первого курса. Она маленькая и будет в репозитории.

**Comment by thevery** [comment]
Ok
