### ISSUE TITLE
почти у всех упал один и тот же тест. 

### ISSUE THREAD

**Issue by baba-beda** [IFMO-MobDev-2014/lesson4#73]
Объясните, пожалуйста, почему тест -----5 не должен вычисляться?
В задании не было прописано о невалидности подобного выражения, и многие из распространенных калькуляторов без проблем вычислят этот тест.

**Comment by knah** [comment]
Также добавлю сюда, что тесты на некорректные выражения 6 и 9 (и возможно другие идейно схожие тесты) не должны быть в наборе тестов вообще. Эти тесты проверяют крайние случаи (null и пустая строка), которые не были оговорены в описании задания, и, как следствие, их обработка может быть произвольной. Тесты, однако, требуют конкретный метод обработки, узнать о котором у нас не было никакой возможности. И нет, это не "единственный разумный метод обработки данных случаев". Не надо так.

**Comment by svasilinets** [comment]
Господа, если у вас есть какой-либо "конкретный метод обработки" данных крайних ситуаций, пожалуйста, напишите нам об этом, и мы вполне вероятно повысим вам балл.  Но также я бы хотел сразу заметить, что падение с npe при обращении к строчке не является обработкой такой ситуации и не будет засчитываться (и не надо его апеллировать).
 Если же вы кидали IllegalAgrumentException, ставили assert-ы или как-либо еще позаботились об этих случаях, напишите нам. 
На сим этот тред считаю закрытым.

**Comment by AVBelyy** [comment]
Считается ли валидным "методом обработки" перехват всех исключений строкой "catch (Exception e)" после запуска CalculationEngine?

Будет ли удовлетворена апелляция к тому, что значения, на которых кидается NPE, никак не могут быть получены через пользовательский интерфейс (а если и могут, то это ошибка интерфейса, а не CalculationException)?

**Comment by knah** [comment]
Совершенно несогласен с

> что падение с npe при обращении к строчке не является обработкой такой ситуации

Бросание NPE в Java является нормой, особенно в ситуации, когда в аргумент передается null вместо разумных данных. В [javadoc для NullPointerException](https://docs.oracle.com/javase/7/docs/api/java/lang/NullPointerException.html) есть следующая фраза:

> Applications should throw instances of this class to indicate other illegal uses of the null object.

Передача null в качестве аргумента является неверным использованием этого самого нулла, поэтому бросок NPE (пусть даже средствами JVM, а не в явном виде) является корректным. Например, так может делать метод [Map.containsKey](https://docs.oracle.com/javase/7/docs/api/java/util/Map.html#containsKey%28java.lang.Object%29) если в его аргумент передать null и контейнер не разрешает нулевые ключи. Аналогичное поведение можно заметить у многих других методов Map и в других местах стандартной библиотеки.
Если тут вам захочется сказать, что Map - интерфейс и не факт что что-то там реально кидает NPE на нулевой аргумент - то есть вполне конкретный метод [HashMap.putAll](https://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html#putAll%28java.util.Map%29) который ведет себя аналогично.
Более того, в книге [Effective Java, 2nd edition](http://uet.vnu.edu.vn/~chauttm/e-books/java/Effective.Java.2nd.Edition.May.2008.3000th.Release.pdf) в главе 60 (печатная страница 248, страница в .pdf 271) явно указано, что на передачу null в аргумент, который не может быть null, необходимо кидать NullPointerException, а использование IllegalArgumentException считается недостаточно хорошим из-за того, что это исключение очень общее.
Стоит заметить, что это не просто очередной самоучитель джавы - это книга написана одним из программистов Sun и считается почти официальными гайдлайнами. [Описание первой редакции книги на сайте Oracle](http://www.oracle.com/technetwork/java/effectivejava-136174.html)

Если же вас беспокоит то, что этот NPE не ловится нигде в интерфейсе - то стоит заметить, что почти всегда интерфейс достаточно умен, чтобы не пихать null куда попало.

**Comment by EvgeniyaKatunina** [comment]
Объясните про тест -----5, пожалуйста, даже калькулятор Windows, на такую строку, вставленную из буфера обмена, выдаёт -5.
