### ISSUE TITLE
There is some issues(

### ISSUE THREAD

**Issue by IlyaHalsky** [IFMO-MobDev-2014/lesson4#80]
New AS doesn't support old gradle, so Studio updates it. And the robolectric dies. Can you update both gradle and robolectric?

**Comment by thevery** [comment]
Have you tried updating roboelectric?

**Comment by IlyaHalsky** [comment]
I did.
And I'm still getting this error: http://tc.thevery.info/viewLog.html?buildId=151&buildTypeId=Ifmo2014_Lesson4&guest=1

**Comment by IlyaHalsky** [comment]
Found old version of AS, finished task on it.

**Comment by IlyaHalsky** [comment]
or not.
